pipeline {

    agent any

    stages {

        stage('Build') {

            steps {

                echo 'Building application...'

            }

        }

        stage('Test') {

            steps {

                echo 'Testing application...'

                sh 'node app.js'

            }

        }

        stage('Deploy') {

            steps {

                echo 'Deployment completed'

            }

        }

    }

}
